### ISSUE TITLE
_tkinter.TclError: missing close-brace

### ISSUE THREAD

**Issue by WK-GiHu** [SchuppiM/Python-tkTable#1]
> The command that is causing the error is os.environ.get("TKTABLE_LIBRARY") returning a None value. 

No, using `"TKTABLE_LIBRARY"` is optional, to point to the library.
But for your issue, it's worth to try and use it.
Look at **Line 134**, there is a comment warning about `TclError: table`

---

    File "C:\...AppData\Local\Programs\Python\Python37-32\Lib\lib-tk\tktable.py", line 126, in __init__ 
    'global auto_path; lappend auto_path {%s}' % tktable_lib) 
    _tkinter.TclError: missing close-brace

>             master.tk.eval(
>                'global auto_path; lappend auto_path {%s}' % tktable_lib)
>
> Braces are there…. Any ideas?

Without knowing the value of `tkable_lib` can't tell anything.
Add a `print(tkable_lib)` before line 126.

### Please, remember to delete the SO Answer.

**Comment by SchuppiM** [comment]
Hmm, not having "TKTABLE_LIBRARY" in place caused the first error. It didn't give me an Option.
In tkable_lib we find what we have in the environment variable "TKTABLE_LIBRARY" I had to create my self.
At the moment I get "C:\Users\mschuppisser.EAD\AppData\Local\Programs\Python\Python37-32\tcl\".

**Comment by WK-GiHu** [comment]
@SchuppiM 

> At the moment I get "C:\Users\mschuppisser.EAD\AppData\Local\Programs\Python\Python37-32\tcl".

Should read: `"C:\...\Python37-32\tcl\Tktable2.11"`, assuming your `.dll` is in `...tcl\Tktable2.11`.
But this does not explain `_tkinter.TclError: missing close-brace`.

Verified with `Python 3.5`, the `master.tk.eval(...` part works for me.
Try to make it **one** line: `master.tk.eval('global auto_path; lappend auto_path {%s}' % tktable_lib)`

**Comment by SchuppiM** [comment]
@WK-GiHu
Yes, the Tktable.dll is in C:\Users\mschuppisser.EAD\AppData\Local\Programs\Python\Python37-32\tcl.
I solved the close-brace, I think it was because of a \ at the end of the path I had in the environment variable "TKTABLE_LIBRARY". I don't know what this command "master.tk.eval('global auto_path; lappend auto_path {%s}' % tktable_lib)" does, but it seems to work now, not 100% sure, but it is not throwing an error any more.
Now the Problem seems to be in "master.tk.call('package', 'require', 'Tktable')"..... don't know what this does, but it is part of this tktable I downloaded.

**Comment by WK-GiHu** [comment]
@SchuppiM 

### Please, remember to delete the SO Answer.

---

>  I don't know what this command 
>  `master.tk.eval('global auto_path; lappend auto_path {%s}' % tktable_lib)`
>  does, but it seems to work now,

The purpose is, to add the path defined in `TKTABLE_LIBRARY` to the internal `tcl` search path.
Now `tcl` knows, where to look for the requested `Tktable` library.

> Now the Problem seems to be in 
> `master.tk.call('package', 'require', 'Tktable')`
>..... don't know what this does, but it is part of this tktable I downloaded.

It's used to set a **flag** to prevent multiple **loading** and **initalisations** of the `Tktable` library.
This shouldn't bother you.

To verify, do:

        import tktable
        table = tktable.Table(root)
        table.grid(row=0, column=0)

You should see a empty Spreadsheet like table:

![grafik](https://user-images.githubusercontent.com/22146250/55167334-0f381a00-5171-11e9-8c1f-af97fb0349a6.png)

**Comment by SchuppiM** [comment]
@WK-GiHu
This is the scriptI run:
import sys
sys.path.insert(0, r"C:\Users\mschuppisser.EAD\AppData\Local\Programs\Python\Python37-32\Lib\lib-tk")

from tkinter import *
import tktable

class app():
    def __init__(self, root):
        table = tktable.Table(root)
        table.grid(row=0, column=0)

root = Tk()
root.title("Test tktable")
application = app(root)
root.mainloop()

This is the Traceback I got:
Traceback (most recent call last):
  File "C:/Users/mschuppisser.EAD/Data/My Data/Python/Test Applikation/TestTKTable.py", line 14, in <module>
    application = app(root)
  File "C:/Users/mschuppisser.EAD/Data/My Data/Python/Test Applikation/TestTKTable.py", line 9, in __init__
    table = tktable.Table(root)
  File "C:\Users\mschuppisser.EAD\AppData\Local\Programs\Python\Python37-32\Lib\lib-tk\tktable.py", line 145, in __init__
    tkinter.Widget.__init__(self, master, 'table', kw)
  File "C:\Users\mschuppisser.EAD\AppData\Local\Programs\Python\Python37-32\lib\tkinter\__init__.py", line 2299, in __init__
    (widgetName, self._w) + extra + self._options(cnf))
_tkinter.TclError: invalid command name "table"

**Comment by WK-GiHu** [comment]
@SchuppiM 

> sys.path.insert(0, r...

Is this realy needed?

---

Add the following and show the output:

        for env in ['TCL_LIBRARY', 'TK_LIBRARY', 'TKTABLE_LIBRARY']:
            print('{}:{}'.format(env, os.environ.get(env)))

**Comment by SchuppiM** [comment]
@WK-GiHu
sys.path.insert(0, r...  Yes, otherwise it can't find tktable in the lib-tk Folder. thought it has to be there... in other filders it can find it without.

Here the Output:
TCL_LIBRARY:C:\Users\mschuppisser.EAD\AppData\Local\Programs\Python\Python37-32\tcl\tcl8.6
TK_LIBRARY:C:\Users\mschuppisser.EAD\AppData\Local\Programs\Python\Python37-32\tcl\tk8.6
TKTABLE_LIBRARY:C:\ActiveTcl\lib
For TKTABLE_LIBRARY I tried this paths too: C:\Users\mschuppisser.EAD\AppData\Local\Programs\Python\Python37-32\tcl\Tktable2.11; C:\ActiveTcl\lib\Tktable2.11 no Change in beavior.
What is interesting is that I had to create the three env. var. myself!?

Reg Edit for PythonPath contains: C:\Users\mschuppisser.EAD\AppData\Local\Programs\Python\Python37-32\Lib\;C:\Users\mschuppisser.EAD\AppData\Local\Programs\Python\Python37-32\DLLs\;C:\Users\mschuppisser.EAD\AppData\Local\Programs\Python\Python37-32\tcl\; C:\ActiveTcl\lib\

**Comment by WK-GiHu** [comment]
@SchuppiM 

> Reg Edit for PythonPath contains:
> `C:\...\Python37-32\tcl;`

Extend this part to `C:\...\Python37-32\tcl\Tktable2.11;`

---

> For TKTABLE_LIBRARY I tried this paths too: C:\Users\mschuppisser.EAD\AppData\Local\Programs\Python\Python37-32\tcl\Tktable2.11

### Please confirm:

- [x] The `tktable.dll` and `*.tcl` files are in `...Python37-32\tcl\Tktable2.11`?
- [x] The ouput of  `print(tkable_lib)` before line 126, is `...Python37-32\tcl\Tktable2.11`?
- [ ] The output of `print(_TKTABLE_LOADED), after line 133`, is `True`?

**Comment by SchuppiM** [comment]
@WK-GiHu
Extend this part to C:\...\Python37-32\tcl\Tktable2.11; Done: Still the same error
 The tktable.dll and *.tcl files are in ...Python37-32\tcl\Tktable2.11: Yes
 The ouput of print(tkable_lib) before line 126, is ...Python37-32\tcl\Tktable2.11: Yes
 The output of print(_TKTABLE_LOADED), after line 133, is True: No, _TKTABLE_LOADED would be set to True after the "master.tk.call('package', 'require', 'Tktable')" Statement, this is failing.
